### ISSUE TITLE
Dodging Removes Certain Buffs?

### ISSUE THREAD

**Issue by ThrasherGX** [ForgottenGlory/POTD#11]
[Save69_7B1264EA_0_4E656C61_BleakFallsBarrow01_000419_20211002010111_11_1.zip](https://github.com/ForgottenGlory/POTD/files/7270683/Save69_7B1264EA_0_4E656C61_BleakFallsBarrow01_000419_20211002010111_11_1.zip)

**LS Version**
Beta 2

**Describe the bug**
Using the dodge roll from Engarde, certain buffs appear to get removed.  At the very least, flame cloak gets removed when using dodge.

**To Reproduce**
Load the attached save, then cast flame cloak, then use dodge.  Flame cloak falls off.

**Expected behavior**
Dodging should not remove spell buffs.

**Additional context**
Based on the buff icons, it appears that the dodge roll adds a conflicting buff that overwrites the flame cloak spell.
This bug also occurs if Incorporeal dodging is enabled.

**Comment by ThrasherGX** [comment]
Update: Apparently Engarde's dodge only removes Flame Cloak, not Frost Cloak or Lightning Cloak.

**Comment by Dace617** [comment]
possible fix in dev channel

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
