### ISSUE TITLE
Duelist Class - Speed Bonus incorrect

### ISSUE THREAD

**Issue by ThrasherGX** [ForgottenGlory/POTD#12]
[Save80_7B1264EA_0_4E656C61_WhiterunBanneredMare_000519_20211002020720_14_1.zip](https://github.com/ForgottenGlory/POTD/files/7270752/Save80_7B1264EA_0_4E656C61_WhiterunBanneredMare_000519_20211002020720_14_1.zip)

**LS Version**
Beta 2

**Describe the bug**
The duelist class is supposed to give 2% increased movespeed per class level, while your left hand is empty.
Instead, it only gives .2%, or 1/10th of the amount claimed.

**To Reproduce**
Load the attached save.  My character is currently a level 8 duelist, which should be a speed increase of 16%, on top of the 10% from the thief stone.  Use the console to get the player's speedmult value.  If this was working correctly, it would be 126, but instead it shows as 111.6.

**Expected behavior**
Player movespeed should be 126 with both Thief Stone and a level 8 Duelist class.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
