### ISSUE TITLE
Face discolor solitude and dragon bridge

### ISSUE THREAD

**Issue by almightycricket** [ForgottenGlory/POTD#13]
Beta 2 POTD

**Describe the bug**
Faces are bald, and seem to be bugged the wrong colors and details.

**To Reproduce**
walk around dragon bridge and solitude and find the npcs in the zip.

**Expected behavior**
to have hair and correct features

**Additional context**
Probably more in other areas, just what I've found
[face discolor bug.zip](https://github.com/ForgottenGlory/POTD/files/7274383/face.discolor.bug.zip)
.

**Comment by almightycricket** [comment]
![Screenshot 2021-10-03 19-31-08](https://user-images.githubusercontent.com/39885855/135784798-a755039f-c91a-4f93-bd85-58f2847f3e45.png)
seranas mother

**Comment by ForgottenGlory** [comment]
Should be fixed already
