### ISSUE TITLE
Temporarily invincible enemies.

### ISSUE THREAD

**Issue by almightycricket** [ForgottenGlory/POTD#15]
POTD beta 2

**Describe the bug** 
When in combat (seen most often with vampires but that may be due to me playing the dawnguard dlc) whilst attacking someone occasionally I'll encounter someone who refuses to be damaged by any attack made. This is semi-permanent and after 3-5 seconds they are affected by damage again.

**To Reproduce**
Get into group combat and be aggressive, eventually you'll encounter and enemy who wont die. It happens often enough within an hour play session. I believe it has to do with the dodge iframe power that is granted and an npc being interrupted right as they were about to dodge.

**Expected behavior**
For damage to be dealt to someone standing still.

I have no screen shots as this happens at random and I can't trigger it at will.

**Comment by ThrasherGX** [comment]
I can confirm that this has also happened to me with Falmer in Mzulft.  I believe it has happened other places as well, it is particularly noticeable as enemies sometimes get a finisher done to them, but don't die afterwards.

**Comment by almightycricket** [comment]
Ah! I forgot that the kill move not working was a thing. I didn't put two and two together. I thought I was interrupted, only noticed the invincible enemies when I was wailing on them normally. Definitely a thing with the killmoves as well.
