### ISSUE TITLE
Missing textures in white river watch basement area

### ISSUE THREAD

**Issue by almightycricket** [ForgottenGlory/POTD#16]
Beta 2 POTD

**Describe the bug**
Missing textures

**To Reproduce**
Go to area indicated at white river watch cave

**Expected behavior**
not see through the environment
[white river watch --cave with blind guard--.zip](https://github.com/ForgottenGlory/POTD/files/7274410/white.river.watch.--cave.with.blind.guard--.zip)
.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
