### ISSUE TITLE
Attacks not working even with engarde correctly set up.

### ISSUE THREAD

**Issue by almightycricket** [ForgottenGlory/POTD#17]
Beta 2

**Describe the bug**
Attacks wont register regardless of engarde settings. This has been reported with or without stamina in certain circumstances. Personally became more noticeable as my attack speed went up.

**To Reproduce**
Attack a lot, eventually will fail when you click. Of note: I tried a different computer mouse, issue persisted.

**Expected behavior**
I left or right click, attack goes off.

**Comment by ThrasherGX** [comment]
I can confirm that I have this issue as well.  Repeated clicking of the mouse will often produce large gaps where my character does not attack at all.

This also seems to occur with Power attacks, although there may just be a cooldown between use for those.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
