### ISSUE TITLE
Perk Awards Redux - Not Working

### ISSUE THREAD

**Issue by ThrasherGX** [ForgottenGlory/POTD#18]
**PotD Version**
Beta 2

**Describe the bug**
The mod Perk Awards Redux is not granting bonus perks.  Enemies tested: Dragons,  Morokei (Dragon Priest), Ancano (Final boss of College questline)

**To Reproduce**
Kill one of the enemies that the Perk Awards Redux ini file lists as granting a perk.  It will not grant a perk.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
