### ISSUE TITLE
Alternative Perspective - Skalei's Scraps missing pelt textures

### ISSUE THREAD

**Issue by Sparkrdom** [ForgottenGlory/POTD#2]
**Describe the bug**
Pelt rug, and two hanging rugs in Skalei's Scraps are missing textures. Reloaded game, disabled/enabled in console

**Screenshots**
https://i.imgur.com/R0cH1tB.jpg
https://i.imgur.com/PiVPaRu.jpg
https://i.imgur.com/Vt4aQoV.jpg
https://i.imgur.com/gbqdwDD.jpg

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
