### ISSUE TITLE
Windhelm Bone altar

### ISSUE THREAD

**Issue by Hydragraphica** [ForgottenGlory/POTD#20]
Potd beta 2 

**Describe the bug**
Windhelm bone altar doesn't exist as the area seems to conflict with either "ClefJ's Winterhold, City Entrances Overhaul - Windhelm, or City Entrances Overhaul - Windhelm" when you "discover" the bone altar and fast travel to it you end up in terrain that contains a live nord and two corpses.

**To Reproduce**
Unlock Bone Collector perk, go to windhelms altar on the map and fast travel

**Expected behavior**
Windhelm having a bone altar and fast travel not putting you into the terrain

**Comment by ForgottenGlory** [comment]
Should be fixed 1.2.0
