### ISSUE TITLE
Ish's Respec Crash

### ISSUE THREAD

**Issue by Deadbeat-Senpai** [ForgottenGlory/POTD#22]
PotD Beta 2
[Respeccrash_Save.zip](https://github.com/ForgottenGlory/POTD/files/7278128/Respeccrash.zip)

**Describe the bug**
CTD on respec potion use

**To Reproduce**
1. Try to respec 
2. CTD
**Expected behavior**
A refund of perk points 

**Screenshots**
![respeccrash](https://user-images.githubusercontent.com/91890116/135856972-25de1189-d9ea-4b85-a144-37b0cb543cba.gif)

**Additional context**
Does not generate a crash report at all, I have tried several times.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
