### ISSUE TITLE
Face discolor radiant raiment

### ISSUE THREAD

**Issue by Hydragraphica** [ForgottenGlory/POTD#23]
POTD Beta 2

**Describe the bug**
Face discolor on Endarie (High Elf/Altmer) at the Radiant Raiment in Solitude

**To Reproduce**
Visit Radiant Raiment in Solitude

**Expected behavior**
A clean face skin

**Screenshots**

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 10 04 - 13 44 31 54](https://user-images.githubusercontent.com/91855599/135899252-8a44e309-832f-407c-bcaf-8e969766be8b.png)

**Comment by ThrasherGX** [comment]
This is a duplicate of issue #13.

**Comment by Hydragraphica** [comment]
oops
