### ISSUE TITLE
Path of Sorcery - Spell Mastery Perk - Triumvirate Spells Not Supported

### ISSUE THREAD

**Issue by ThrasherGX** [ForgottenGlory/POTD#24]
[Save292_7B1264EA_0_4E656C61_WinterholdTheFrozenHearth_010359_20211006011413_30_1.zip](https://github.com/ForgottenGlory/POTD/files/7297279/Save292_7B1264EA_0_4E656C61_WinterholdTheFrozenHearth_010359_20211006011413_30_1.zip)

**LS Version**
Beta 2

**Describe the bug**
The Alteration perk Spell Mastery does not work for spells from Triumvirate.  

**To Reproduce**
Load the attached save, put a point into the spell mastery perk in the Alteration tree.  Then cast any of the triumvirate shadow spells, they will not be mastered.  Then cast any vanilla spell, it will get mastered.

**Expected behavior**
All spells should be supported for the spell mastery perk.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
