### ISSUE TITLE
CTD when trying to return Meridia's Beacon to it's pedestal.

### ISSUE THREAD

**Issue by Audixas** [ForgottenGlory/POTD#28]
**LS Version**
Beta 3.

**Describe the bug**
The game crashes to desktop after putting Meridia's Beacon into it's pedestal.

**To Reproduce**
1. Acquire Meridia's Beacon.
2. Travel to her shrine and try to return the Beacon.
3. Crash to desktop.

**Expected behavior**
The Beacon is put in it's place and the player is moved up into the air to talk with Meridia.

**Save file**
[Save103_35A27992_0_4175726F7261_Tamriel_001051_20211021120710_25_1.zip](https://github.com/ForgottenGlory/POTD/files/7392349/Save103_35A27992_0_4175726F7261_Tamriel_001051_20211021120710_25_1.zip)

**Comment by TwistedModding** [comment]
please attach a crashlog

**Comment by Audixas** [comment]
There is no crash log.

**Comment by Jamalach** [comment]
Can confirm that this issue exists and is reproducible. I looked, but there was no NetScriptFramework crash log generated from the CTD. 

I tried stepping through the quest stages for the Meridia quest (DA09) and the crash always occured on stage 200. Skipping to 300 doesn't crash it, but also doesn't remove the rocks blocking the entrance to Mount Kilkreath dungeon.

**Comment by MyDataTrends** [comment]
Another user had a crash log associated with this if of help
[Crash_2021_10_15_16-9-4.txt](https://github.com/ForgottenGlory/POTD/files/7449115/Crash_2021_10_15_16-9-4.txt)

**Comment by Audixas** [comment]
> Another user had a crash log associated with this if of help [Crash_2021_10_15_16-9-4.txt](https://github.com/ForgottenGlory/POTD/files/7449115/Crash_2021_10_15_16-9-4.txt)

This is my crashlog, but it's not related to the issue.

**Comment by SilimSavertin** [comment]
I've played around with the console to see if the quest is potentially finishable otherwise, but even getting access into the dungeon won't help as another crash without log happens the moment you pick up the sword at the end.

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
