### ISSUE TITLE
Sets of Skills MCM settings not correct

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/POTD#29]
POTD Beta 3

**Describe the bug**
MCM settings for Sets of Skills are default. i.e: hardcore not enabled.

**To Reproduce**
Start the game. check Sets of Skills MCM

**Expected behavior**
Hardcore mode to be enabled, class limit set to 2

Either change the MCM steps in the readme to reflect that these settings need to be set or fix up the automated MCM

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
