### ISSUE TITLE
Skyrim Bandits cannot be looted

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/POTD#3]
PotD Beta 1 1.00

**Describe the bug**
cannot loot skyrim bandits, there is no prompt on the bodies and trying to use any of quickloots keys does nothing

**To Reproduce**
kill skyrim bandit, try to loot.

**Expected behavior**
to be able to get my loot

**Screenshots**

![enb2021_9_28_10_37_44](https://user-images.githubusercontent.com/38520983/135004263-7d22599b-957e-4113-99c8-8a3bce3b64ef.png)

**Additional context**
Heritage bandits work correctly, as do animals

**Comment by DrFrosty21** [comment]
Add Draugr and Imperial Soldiers to the list.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
