### ISSUE TITLE
Bridge to Windhelp Oddness

### ISSUE THREAD

**Issue by MyDataTrends** [ForgottenGlory/POTD#30]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash` - No crash

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
PotD 1.0.0

**Describe the bug**
Looks like arches on bridge to Windhelm aren't correct.

**To Reproduce**
Walk to Windhelm

**Expected behavior**
Full arches or no arches.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed. - Screenshots attached
![Bug PotD 2](https://user-images.githubusercontent.com/89560881/139558069-0e45616a-e6fd-4ce0-a509-042a70ae18f1.png)
![Bug PotD 1](https://user-images.githubusercontent.com/89560881/139558071-6f984e36-8862-453e-aee2-17ee22cfe129.png)

**Additional context**
Dace said this was a known issue in Beta 3 (unclear if we're remembering correctly though)

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
