### ISSUE TITLE
Alternate Perspective Helgen Main Quest Stuck at Carriage

### ISSUE THREAD

**Issue by ektorasgr** [ForgottenGlory/POTD#32]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 3

**Describe the bug**
Alternate Perspective Helgen Main Quest Stuck at Carriage. All the prisoners get off the carriage but nothing happens, it doesnt proceed. General tulius is also standing away from where the headsman is. 

I uploaded 3 saves, one is before i enter Helgen, one is after sleeping at the inn, and one is at the point where everyone is stuck and nothing is happening

[165.zip](https://github.com/ForgottenGlory/POTD/files/7448198/165.zip)
[164.zip](https://github.com/ForgottenGlory/POTD/files/7448197/164.zip)
[163.zip](https://github.com/ForgottenGlory/POTD/files/7448199/163.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed 1.1.0
