### ISSUE TITLE
Perk Point Awards Redux not consistently awarding perks

### ISSUE THREAD

**Issue by Jamalach** [ForgottenGlory/POTD#33]
**POTD Version**
1.0

**Describe the bug**
Dragons (and sometimes some named NPC's) aren't consistently giving perk points on death.

**To Reproduce**
Kill a dragon yourself. (without using followers/conjured minions/environmental effects)

**Expected behavior**
Every time you kill a dragon, or one of the NPC's listed in Perk Point Awards Redux you should recieve 1 (or sometimes 3) perk points, but never 0.

**Screenshots**

**Additional context**
The effect on the NPC that says it should give the perk on death seems to be there, but sometimes fails to actually fire off. 
I initially discovered the bug when finishing the civil war quest when it failed to give me extra perk points for killing Ulfric, and then slightly later on failed to get perk points from a dragon either. 
I spawned in Ulfric and actually did recieve the perk points when I killed him for the second time, hence why it's a consistency issue, instead of jsut straight up not working.

**Comment by ForgottenGlory** [comment]
Will fix when mod is fixed, named NPCs currently aren't working. Not sure why.
