### ISSUE TITLE
Destruction perks not working

### ISSUE THREAD

**Issue by mageeron** [ForgottenGlory/POTD#34]
**POTD Version 1.0.0 **

**Describe the bug**
Some destruction perks don't work at all some only partially. They are mostly ordinator perks. Didn't test other perk trees. 

Ordinator perks not working at all:
Static Field / Arc Burn / Magnetize / Electroconvulsions / Stormblast(in game notification and effect but no spell fired) / 
Harsh Lesson / Frostfall (no reduction in attack damage, water part works ok) / Crystalize / Shatter / Glacial Prison /
Scarring Burns / Flash Fire / Conflagration / Scorched Earth 

other destruction perks bugs : 
Augmented Shock -doesn't give electric resist
Feedback -doesn't work
Crown of Inferno/Storms/Winter -missing description about 75% resist that they give

**Comment by ForgottenGlory** [comment]
Should be fixed 1.2.0
