### ISSUE TITLE
Freeze when exiting werewolf form

### ISSUE THREAD

**Issue by RnBuck** [ForgottenGlory/POTD#37]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
1.0.0
**Describe the bug**
When exiting the werewolf form back to human the game freezes
**To Reproduce**
enter werewolf form and wait until it runs out and you get reverted back
**Expected behavior**
the game doesn`t freeze and i can continue playing on
**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
I produced the freeze three times so far and sometimes it takes a little longer (like two seconds after going back to human form) until it freezes

**Comment by AldoMaldera** [comment]
Same Problem.

**Describe the bug**
When exiting the werewolf form back to human the game freezes

**Possible relevant objects**
Mod: _Hand to Hand Rebalance - Race Attack Fix.esp_

Disabling the mod, i have no issues. 

[Crash_2021_12_1_0-49-17.txt](https://github.com/ForgottenGlory/POTD/files/7634248/Crash_2021_12_1_0-49-17.txt)
