### ISSUE TITLE
Breath and Form does not reduce stamina cost of sprinting

### ISSUE THREAD

**Issue by SteveDennick** [ForgottenGlory/POTD#39]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
POTD Beta 3

**Describe the bug**
Breath and Form (Speech perk) does not grant reduced stamina cost of sprinting. Likely a conflict with engarde's walk, run and sprint rework

10% power attack stamina cost reduction works as expected, so perk is partially working

**To Reproduce**
Take the perk

**Expected behavior**
"sprinting consumes very little stamina"

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Possibly fixed 1.2.0
