### ISSUE TITLE
Winterhold - Buildings vanish while moving around

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/POTD#4]
**PotD Version**
Beta 1

**Describe the bug**
Parts of Winterhold try to escape the mortal realm (see gif)

**To Reproduce**
Visit Winterhold

**Expected behavior**
A stable Winterhold

**Screenshots**
https://imgur.com/fqndSKr

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
