### ISSUE TITLE
Dragonbridge

### ISSUE THREAD

**Issue by Klaptafeltje** [ForgottenGlory/POTD#41]
**LS Version**
1.5.97.0

**Describe the bug**
Graphical glitch (likely due mod conflict)

**To Reproduce**
Just walk to Dragonbridge

**Expected behavior**
different objects go through each other (likely due two versions of dragonbridge) 

**Screenshots**
https://imgur.com/a/n9HVPQB

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
