### ISSUE TITLE
Game crashes when placing Meridia's Beacon

### ISSUE THREAD

**Issue by PlausiblyXeno** [ForgottenGlory/POTD#42]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash_2021_12_31_2-4-36.txt](https://github.com/ForgottenGlory/POTD/files/7797229/Crash_2021_12_31_2-4-36.txt)

**LS Version**
Version 1.0.0.1

**Describe the bug**
When I place Meridia's beacon on the space directed by the quest, the game freezes for a few seconds, then it closes to desktop.  I've attempted to load an earlier save and then try, but the same crash occured.

**To Reproduce**
I have a save right in front of Meridia's statue where you place the beacon.  I load that save, then I place the beacon where indicated by the quest, and then the game crashes.

**Expected behavior**
Normally during this quest, after the beacon is placed, you are sent into the sky to speak to Meridia.

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
