### ISSUE TITLE
Unable to improve loot generated items

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/POTD#43]
**PotD Version**
1.0

**Describe the bug**
looted weapons and armor (enchanted or not) can't be improved due to missing recipes

**To Reproduce**
loot equipment and check the grindstone/workbench, it stays empty

**Expected behavior**
Upgrading equipment

**Screenshots**

**Additional context**
Quote from Dace:
_The reason was that the loot patcher makes every enchanted item you find as an actual item. i.e: it's not just an iron sword with xxx enchantment, it's actually a brand new item: iron sword of xxx and they don't come with temper recipes_

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
