### ISSUE TITLE
xLODGEN files missing from MEGA

### ISSUE THREAD

**Issue by matthewcheng64** [ForgottenGlory/POTD#45]
**LS Version**
1.1.0

**Describe the bug**
MEGA hosted file for xLODGEN.85 is no longer available.

**To Reproduce**
1. Manually go to the file link shown by Wabbajack log: https://mega.nz/file/kNRCHRDY#ONIMDnlxyyBH-QsSUgatbQJWOgGGrr8F8bxWD_-bSGc
2. Additionally try the xLODGEN.84 link on Troubleshooting POTD page: https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg

**Expected behavior**
xLODGEN files should be hosted on MEGA

**Screenshots**
Wabbajack Logs:
![Wabbajack Log](https://user-images.githubusercontent.com/71508925/150020866-26e25288-ab14-4957-814f-e89acf1c4797.png)

xLODGEN.84 Link from Troubleshooting POTD page:
![xLODGEN 84 Link](https://user-images.githubusercontent.com/71508925/150020867-f1b41b66-cf79-45d0-a5b6-3ecd4ac6f2a6.png)

xLODGEN.85 Link from Wabbajack error logs:
![xLODGEN 85 Link](https://user-images.githubusercontent.com/71508925/150020868-272d0162-74f9-451a-b27e-2771bb015f18.png)

**Additional context**
I also tried downloading xLODGEN.86 beta which is publically available and moving it to the Wabbajack download folder and renaming to xLODGen.85.7z and xLODGen.84.7z but Wabbajack was unable to recognize it.

**Comment by ForgottenGlory** [comment]
Fixed 1.2.0
