### ISSUE TITLE
Riverwood Chicken holds a lot of custom spellbooks

### ISSUE THREAD

**Issue by IranianVoodooDoctor** [ForgottenGlory/POTD#47]
**LS Version**
1.1.0

**Describe the bug**
I enter Riverwood on a new game for the first time, and a wolf killed a random chicken. I kill the wolf and loot it and when I go to look the chicken, I notice that it has 20+ new spellbooks on hand, of all spell categories and mastery. 

**To Reproduce**
Steps to reproduce the behavior: Go to Riverwood -> Find certain chicken -> Kill Chicken -> Check corpse and you'll find the spellbooks.

**Expected behavior**
No spellbooks on chicken

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 24 - 18 36 26 02](https://user-images.githubusercontent.com/77650214/150846069-9a863996-5e6d-4423-8c60-b7517f63cb08.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 24 - 18 45 16 86](https://user-images.githubusercontent.com/77650214/150846093-d92eedc0-9fd3-4b38-8e5f-a7f9f304b85c.png)

**Additional context**
May apply to other chickens? I resurrected it and killed it via console and it did not have the tremendous amount of spellbooks

**Comment by ForgottenGlory** [comment]
Fixed 1.2.0
