### ISSUE TITLE
Sven has black-face bug

### ISSUE THREAD

**Issue by IranianVoodooDoctor** [ForgottenGlory/POTD#48]
**LS Version**
1.1.0

**Describe the bug**
Sven in Riverwood has the black-face bug. Rest of his body has white skin.

**To Reproduce**
Step into Riverwood Inn where he is and he should have it. 

**Expected behavior**
He shouldn't have a black face

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 24 - 19 07 07 51](https://user-images.githubusercontent.com/77650214/150849070-12b0bdd4-bf13-4685-a81c-59262af585f8.png)

**Additional context**
Tried reloading and disable/enable, did not work.

**Comment by ForgottenGlory** [comment]
Fixed 1.2.0
