### ISSUE TITLE
ClefJ's Winterhold conflict

### ISSUE THREAD

**Issue by Dragozino** [ForgottenGlory/POTD#5]
**PoTD Version**
Beta 1

**Describe the bug**
Embers XD conflict with ClefJ's Winterhold in The Frozen Hearth

**To Reproduce**
Visit the frozen hearth

**Expected behavior**
![imagine](https://staticdelivery.nexusmods.com/mods/1704/images/41409/41409-1603292396-1383901306.jpeg)

**Screenshots**
![image](https://user-images.githubusercontent.com/65357334/135164304-ec444b04-ee72-4fb1-9c22-1b7afcf586cb.png)

**Additional context**
![image](https://user-images.githubusercontent.com/65357334/135164486-7b5865d4-9803-4bfc-aac8-0cb3f3277ec6.png)

**Comment by ForgottenGlory** [comment]
Fixed 1.1.0
