### ISSUE TITLE
Unable to select Bonecraft from the Conjuration Perk Tree

### ISSUE THREAD

**Issue by Kyle-sys** [ForgottenGlory/POTD#56]
**POTD Version**
1.2.0.

**Describe the bug**
It looks like if you pick the Bone Collector perk it disables access to Bonecraft.

**To Reproduce**
1: Level up the Conjuration perk tree to like 25 or so.
2: Get a couple of Perk Points.
3: Obtain Conjuration Mastery.
4: Select Bone Collector.

**Expected behavior**
They should both be able to be selected unless done on purpose.

**Screenshots**
![Skyrim Special Edition 2_12_2022 10_15_30 PM](https://user-images.githubusercontent.com/52866222/153736749-daca122b-8864-4ce7-bded-6272bed86658.png)

**Additional context**
I don't know if this is a bug or not.

**Comment by thehajo** [comment]
Not a bug, intentional change made by mod author of Vokriinator Black

**Comment by Kyle-sys** [comment]
Okay, thank you for the information. I'll go ahead and close this issue.
