### ISSUE TITLE
Windhelm - Clipping and loading issues

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/POTD#6]
**PotD Version**
Beta 1

**Describe the bug**
Found some clipping/loading issues inside of Windhelm

**To Reproduce**
Visit Windhelm

**Expected behavior**
A stable Windhelm

**Screenshots**
https://imgur.com/a/ILEBCvQ

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
