### ISSUE TITLE
Failed to download through Wabbajack

### ISSUE THREAD

**Issue by driggs423** [ForgottenGlory/POTD#75]
**LS Version**
1.2.0

**Describe the bug**
failed to download one or more archives

**To Reproduce**
trying to download modlist

**Expected behavior**
modlist to finish downloading then install

**Additional context**
Log notes for when it closed--
360.67 - Loading ModLists from GitHub
361.24 - Error downloading modlist image OME(FT)
361.24 - Error downloading modlist image OME(FT)
506.31 - Starting to install Path of the Dovahkiin
506.32 - Starting Installer Task
506.32 - Installation has Started
506.32 - File hash check (-42) 62ddbf2c4bf1db4cf28d770285f57b7ad4eb96d40ecf39daa499ab8a5763e6b9
506.54 - Configuring Processor
506.54 - Install Folder: C:\Path of the Dovahkin
506.54 - Downloads Folder: C:\Path of the Dovahkin Download
506.54 - Game Folder: C:\Games\Steam\steamapps\common\Skyrim Special Edition
506.54 - Wabbajack Folder: C:\wabbajack\2.5.3.9
506.54 - Drive watcher is starting. Will warn at 8GB and error at 4GB
506.54 - Starting Drive watcher on C:\ currently 273.5GB free out of 465GB
506.54 - Validating Game ESMs
506.55 - Creating Output Folders
506.67 - Optimizing ModList
506.67 - Optimizing ModList directives
507.26 - Looking for files to delete
507.26 - Cleaning empty folders
507.56 - Looking for unmodified files
507.82 - Updating ModList
507.82 - Optimized 88835 directives to 88835 required
507.84 - Hashing Archives
507.84 - Looking for files to hash
507.94 - Found 735 total files, 509 matching filesize
508 - Downloading Missing Archives
508 - Missing 2 archives
508 - Getting Nexus API Key, if a browser appears, please accept
508 - Loading server whitelist
508.2 - Loaded permissions for 653 servers and 292 Google Drive files
508.2 - Getting upgrades list
508.4 - File hash check (-42) 62ddbf2c4bf1db4cf28d770285f57b7ad4eb96d40ecf39daa499ab8a5763e6b9
508.46 - Downloading Paper Maps SE V1.1.zip
508.46 - Downloading xLODGen.86.7z
508.62 - File hash check (-42) 62ddbf2c4bf1db4cf28d770285f57b7ad4eb96d40ecf39daa499ab8a5763e6b9
508.88 - Hashed download is incorrect
508.88 - Loading for alternative to c4CZLrOUle8=
508.88 - No alternative for c4CZLrOUle8= could be found
509.18 - Loading for alternative to MDisdI/y43Q=
509.18 - No alternative for MDisdI/y43Q= could be found
509.23 - Hashing Remaining Archives
509.24 - Looking for files to hash
509.33 - Found 735 total files, 509 matching filesize
509.42 - Unable to download Paper Maps SE V1.1.zip (GoogleDriveDownloader+State|1mfTQy2HIsdz8WWuTLDgiOR-t_IBZyTQC)
509.42 - Unable to download xLODGen.86.7z (MegaDownloader+State|https://mega.nz/file/8Iog2abQ#0rQzamCU_uv68QpnBjvlR8SSepyek7LM6sow4rQFh_c)
509.42 - Cannot continue, was unable to download one or more archives
509.42 - File hash check (-42) 62ddbf2c4bf1db4cf28d770285f57b7ad4eb96d40ecf39daa499ab8a5763e6b9
509.42 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
509.57 - File hash check (-42) 62ddbf2c4bf1db4cf28d770285f57b7ad4eb96d40ecf39daa499ab8a5763e6b9

**Comment by ForgottenGlory** [comment]
K

**Comment by driggs423** [comment]
closed? it still won't download is there something I'm doing wrong?

**Comment by DrFrosty21** [comment]
download issues aren't a bug, please check the discord to get further help. https://www.fgsmodlists.com/
