### ISSUE TITLE
Crash during Helgen Intro

### ISSUE THREAD

**Issue by ThrasherGX** [ForgottenGlory/POTD#9]
[Crash_2021_9_30_19-27-0.txt](https://github.com/ForgottenGlory/POTD/files/7263251/Crash_2021_9_30_19-27-0.txt)
[Save23_7B1264EA_0_4E656C61_Tamriel_000131_20211001001332_2_1.zip](https://github.com/ForgottenGlory/POTD/files/7263265/Save23_7B1264EA_0_4E656C61_Tamriel_000131_20211001001332_2_1.zip)

**PotD Version**
Beta 2

**Describe the bug**
When attempting to do the intro in Helgen via talking to the innkeeper.  Everything works normally, until you get to the part of the into where Hadvar tells you to "stay close to the wall".  Shortly after this, right as Alduin lands on the wall, the game crashes to desktop.  Happened two times in a row.

**To Reproduce**
Load the save attached here, and wait for the into to progress.  Follow along as normal, and when you get to the part mentioned above, the game will crash.

**Expected behavior**
No crash.

**Comment by ThrasherGX** [comment]
As an update to the above, I used the messenger to skip to the escape tunnel part of the quest, which allowed me to bypass the bug above, however when exiting the cave, the game crashed right as Alduin flew overhead.

[Save31_7B1264EA_0_4E656C61_HelgenKeep01_000146_20211001010711_2_1.zip](https://github.com/ForgottenGlory/POTD/files/7263404/Save31_7B1264EA_0_4E656C61_HelgenKeep01_000146_20211001010711_2_1.zip)

Save is right before exiting the cave, so you should only need to leave the cave and wait for Alduin to fly over, causing the crash.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
